name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Stage 1: Checkout
    - name: Checkout Code
      uses: actions/checkout@v4

    # Stage 2: Build
    - name: Build Project
      run: |
        echo "Starting the build process..."
       # make build  # Replace with your build command

    # Stage 3: Test
    - name: Run Tests
      run: |
        echo "Running tests..."
        # make test   # Replace with your test command

    # Stage 4: Deploy
    - name: Deploy Application
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        echo "Deploying application..."
       # make deploy # Replace with your deployment command

    # Stage 5: Notify
    - name: Send Notification
      run: |
        echo "Pipeline completed. Sending notification..."
        curl -X POST -H 'Content-type: application/json' \
             --data '{"text":"CI Pipeline completed successfully!"}' \
             https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX
